---
- hosts: "all"



  roles:

    - role: "artefactual.elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"

    - role: "artefactual.percona"
      become: "yes"
      tags:
        - "percona"

    - role: "artefactual.memcached"
      become: "yes"
      tags:
        - "memcached"

    - role: "artefactual.gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "artefactual.nginx"
      become: "yes"
      tags:
        - "nginx"

    - role: "geerlingguy.composer"
      become: "yes"
      tags:
        - "composer"

    - role: "artefactual.atom"
      become: "yes"
      tags:
        - "atom"
