#archivematica-storage-service.install

install/storage-service.gunicorn-config.py /etc/archivematica/
install/storageService.logging.json /etc/archivematica/
install/storage etc/nginx/sites-available/
install/.storage-service var/archivematica/
install/make_key.py var/archivematica/storage-service/
storage_service/* /usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/storage_service/
