#!/bin/bash

#postrm 
#run after the package is uninstalled

echo "postrm" $1
if [ $1 = "remove" ]; then
    #clean up storage service directories
    rm -rf /usr/share/python/archivematica-storage-service
    rm -rf /usr/share/archivematica/virtualenvs/archivematica-storage-service
    rm -rf /var/archivematica/storage*
    rm -r /etc/default/archivematica-storage-service
    rm -f /tmp/storage_service.log
    rm -f /etc/nginx/sites-enabled/storage
    rm -f /etc/nginx/sites-available/storage
    rm -f /etc/uwsgi/apps-enabled/storage.ini
    rm -f /etc/uwsgi/apps-available/storage.ini
    rm -rf /usr/lib/archivematica/storage*
fi

if [ "$1" = "purge" ]; then
    rm -f /etc/default/archivematica-storage-service
    if which ucf >/dev/null 2>&1; then
        ucf --purge /etc/default/archivematica-storage-service
        ucfr --purge archivematica-storage-service /etc/default/archivematica-storage-service
    fi
fi

exit 0

#DEBHELPER#

