#!/bin/sh

if [ "$1" = "purge" ]; then
    rm -f /etc/default/archivematica-mcp-client
    if which ucf >/dev/null 2>&1; then
        ucf --purge /etc/default/archivematica-mcp-client
        ucfr --purge archivematica-mcp-client /etc/default/archivematica-mcp-client
    fi
fi
