# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  # VirtualBox Guest Additions not installed in "centos/7" box, using bridge device for now!
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.66"
  config.vm.network "public_network"

  # VirtualBox Guest Additions not installed in "centos/7" box, using rsync for now!
  config.vm.synced_folder "../", "/am-packbuild", type: "rsync", rsync__enclude: ".git/"
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo cp /am-packbuild/rpm-testing/archivematica.repo /etc/yum.repos.d
    sudo yum --enablerepo=archivematica clean metadata
    sudo yum update -y
    sudo yum install -y epel-release python-pip
    sudo yum install -y siegfried archivematica-storage-service archivematica-storage-service-frontend
    systemctl enable archivematica-storage-service
    systemctl enable nginx
    systemctl start archivematica-storage-service
    systemctl start nginx
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    # Not working yet! As archivematica user...
    # export $(cat /etc/sysconfig/archivematica-storage-service)
    # cd /usr/share/archivematica/storage-service
    # /usr/lib/archivematica/storage-service/bin/python manage.py migrate
    # /usr/lib/archivematica/storage-service/bin/python manage.py collectstatic --noinput

    ip addr | grep "dynamic eth1"
  SHELL

end
