# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  unless Vagrant.has_plugin?("vagrant-vbguest")
    raise 'vagrant-vbguest plugin not installed!'
  end
  config.vm.network "private_network", ip: "192.168.33.2"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.synced_folder "../", "/am-packbuild", type: "virtualbox"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
  config.vm.provision "shell",
    inline: "/am-packbuild/rpm-EL7-testing/install.sh",
    env: {
      "LOCAL_REPOSITORY" => ENV.fetch('LOCAL_REPOSITORY', 'no'),
      "SEARCH_ENABLED" => ENV.fetch('SEARCH_ENABLED', 'no'),
    }
end
