#!/bin/sh
# source debconf stuff
. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql

# Set the default database encoding to UTF8
dbc_mysql_createdb_encoding="UTF8"

dbc_go archivematica-mcp-server $@

# Create sharedDirectory and rsync content
mkdir -p /var/archivematica/sharedDirectory/
chown -R archivematica:archivematica /var/archivematica/

# Create logs dir
logdir=/var/log/archivematica/MCPServer
mkdir -p $logdir
chown -R archivematica:archivematica $logdir
chmod -R g+s $logdir

# Remove dh-virtualenv build path in editable pip requirements and other local/bin files
# https://github.com/spotify/dh-virtualenv/issues/134
# https://github.com/archivematica/Issues/issues/903
for filename in /usr/share/archivematica/virtualenvs/archivematica-mcp-server/local/bin/* \
    /usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/*.pth \
    /usr/share/archivematica/virtualenvs/archivematica-mcp-server/lib/python2.7/site-packages/*.egg-link ; do
    if [ -f "$filename" ]; then
        sed -i "s/\/src\/src\/archivematica\/src\/MCPServer\/debian\/archivematica-mcp-server//g" $filename
    fi
done

# Populate default mysql config
DBPASS=$(grep "dbc_dbpass=" /etc/dbconfig-common/archivematica-mcp-server.conf| cut -d\= -f2- | tr -d \')
sed -i "s/^\(ARCHIVEMATICA_MCPSERVER_CLIENT_PASSWORD=\).*/\1$DBPASS/g" /etc/default/archivematica-mcp-server

DBUSER=$(grep "dbc_dbuser=" /etc/dbconfig-common/archivematica-mcp-server.conf| cut -d\= -f2- | tr -d \')
sed -i "s/^\(ARCHIVEMATICA_MCPSERVER_CLIENT_USER=\).*/\1$DBUSER/g" /etc/default/archivematica-mcp-server

DBNAME=$(grep "dbc_dbname=" /etc/dbconfig-common/archivematica-mcp-server.conf| cut -d\= -f2- | tr -d \')
sed -i "s/^\(ARCHIVEMATICA_MCPSERVER_CLIENT_DATABASE=\).*/\1$DBNAME/g" /etc/default/archivematica-mcp-server

# Use ucf to preserve user changes in the default file
ucfr archivematica-mcp-server /etc/default/archivematica-mcp-server
ucf --debconf-ok /etc/default/archivematica-mcp-server /etc/default/archivematica-mcp-server

#DEBHELPER#

