#!/bin/bash


logdir=/var/log/archivematica/dashboard
mkdir -p $logdir
chown -R archivematica:archivematica $logdir
chmod -R g+s $logdir

# TODO Remove this from the postinst of any version that is not updating Django
# Remove .pyo's so Django uninstalls properly (See https://github.com/pypa/pip/issues/2209)
echo "Removing Django's .pyo files to aid upgrade"
find /usr/local/lib/python2.7/dist-packages/django/ -name '*.pyo' -delete

# Install & upgrade dashboard requirements
pip install --upgrade -r /usr/share/archivematica/dashboard/requirements.txt

# Create Django key
KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
sed -i "s/CHANGE_ME_WITH_A_SECRET_KEY/\"$KEY\"/g" /etc/default/archivematica-dashboard

# Populate default mysql config
DBPASS=$(grep "dbc_dbpass=" /etc/dbconfig-common/archivematica-mcp-server.conf| cut -d\= -f2- | tr -d \')
sed -i "s/^\(ARCHIVEMATICA_DASHBOARD_CLIENT_PASSWORD=\).*/\1$DBPASS/g" /etc/default/archivematica-dashboard

DBUSER=$(grep "dbc_dbuser=" /etc/dbconfig-common/archivematica-mcp-server.conf| cut -d\= -f2- | tr -d \')
sed -i "s/^\(ARCHIVEMATICA_DASHBOARD_CLIENT_USER=\).*/\1$DBUSER/g" /etc/default/archivematica-dashboard

DBNAME=$(grep "dbc_dbname=" /etc/dbconfig-common/archivematica-mcp-server.conf| cut -d\= -f2- | tr -d \')
sed -i "s/^\(ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE=\).*/\1$DBNAME/g" /etc/default/archivematica-dashboard

# Use ucf to preserve user changes in the default file
ucfr archivematica-dashboard /etc/default/archivematica-dashboard
ucf --debconf-ok /etc/default/archivematica-dashboard /etc/default/archivematica-dashboard

#this is required to allow syncdb to work properly
export $(cat /etc/default/archivematica-dashboard)

# Fake migrations if necessary.  $2 is old version
if [[ $2 == '1:1.4.1'* ]]; then
    echo 'Faking 1.4.1 database setup'
    /usr/share/archivematica/dashboard/manage.py migrate --fake --settings='settings.production'
    /usr/share/archivematica/dashboard/manage.py migrate administration 0001_initial --fake --settings='settings.production'
    /usr/share/archivematica/dashboard/manage.py migrate main 0002_initial_data --fake --settings='settings.production'
    /usr/share/archivematica/dashboard/manage.py migrate fpr 0002_initial_data --fake --settings='settings.production'
fi

# Run migrations
/usr/share/archivematica/dashboard/manage.py migrate --settings='settings.production'

# Collect static content
/usr/share/archivematica/dashboard/manage.py collectstatic --noinput --clear


#DEBHELPER#
