name: Archivematica RPM Packages Test
on:
  workflow_dispatch:
    inputs:
      archivematica_packages_repo_version:
        description: "Archivematica packages repository version (e.g. 1.18.x)"
        required: false
        default: "1.18.x"
        type: "string"
      archivematica_packages_repo_baseurl:
        description: "Optional Archivematica RPM repository base URL"
        required: false
        default: ""
        type: "string"
      build_packages:
        description: "Build local packages"
        required: true
        default: true
        type: "boolean"
  pull_request:
    paths:
      - "rpms/EL9/archivematica/**"
      - "rpms/EL9/archivematica-storage-service/**"
      - "tests/archivematica/**"
      - "!tests/archivematica/README.md"
      - "!tests/archivematica/{jammy,noble}/**"
  push:
    branches:
      - "stable/**"
      - "qa/**"
    paths:
      - "rpms/EL9/archivematica/**"
      - "rpms/EL9/archivematica-storage-service/**"
      - "tests/archivematica/**"
      - "!tests/archivematica/README.md"
      - "!tests/archivematica/{jammy,noble}/**"
  schedule:
    - cron: "0 2 * * *"

env:
  ARCHIVEMATICA_PACKAGES_REPO_VERSION: ${{ inputs.archivematica_packages_repo_version || '1.18.x' }}
  ARCHIVEMATICA_PACKAGES_REPO_BASEURL: ${{ inputs.archivematica_packages_repo_baseurl || '' }}
jobs:
  build-am-packages:
    name: Build Archivematica packages
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    steps:
    - name: Check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Build
      run: |
        make -C ${{ github.workspace }}/rpms/EL9/archivematica
    - name: Save artifacts
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: archivematica-packages
        path: |
          ${{ github.workspace }}/rpms/EL9/archivematica/*.rpm
  build-ss-packages:
    name: Build Storage Service packages
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    steps:
    - name: Check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Build
      run: |
        make -C ${{ github.workspace }}/rpms/EL9/archivematica-storage-service
    - name: Save artifacts
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: archivematica-storage-service-packages
        path: |
          ${{ github.workspace }}/rpms/EL9/archivematica-storage-service/*.rpm
  create-package-repo:
    name: Create package repository
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    needs:
    - build-am-packages
    - build-ss-packages
    steps:
    - name: Check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Restore Archivematica packages
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: archivematica-packages
        path: |
          ${{ github.workspace }}/rpms/EL9/archivematica/
    - name: Restore Storage Service packages
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: archivematica-storage-service-packages
        path: |
          ${{ github.workspace }}/rpms/EL9/archivematica-storage-service
    - name: Create repository
      run: |
        make -C ${{ github.workspace }}/rpms/EL9 createrepo
    - name: Save package repository
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: package-repository
        path: |
          ${{ github.workspace }}/rpms/EL9/_yum_repository
  test:
    name: Test packages
    needs: create-package-repo
    runs-on: ubuntu-22.04
    if: >-
      ${{
        always() && (
          needs.create-package-repo.result == 'success' ||
          (github.event_name == 'workflow_dispatch' && inputs.build_packages == false)
        )
      }}
    env:
      build_packages: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    steps:
    - name: Check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Restore package repository
      if: needs.create-package-repo.result == 'success'
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: package-repository
        path: ${{ github.workspace }}/rpms/EL9/_yum_repository
    - name: "Upgrade crun (supports Ubuntu's systemd in the Dockerfile)"
      run: |
        wget https://github.com/containers/crun/releases/download/1.15/crun-1.15-linux-amd64
        sudo install crun-1.15-linux-amd64 /usr/bin/crun
        rm crun-1.15-linux-amd64
    - name: "Prepare Archivematica test environment"
      uses: ./.github/actions/setup-am-tests-venv
      with:
        codename: rocky9
    - name: "Start the Compose environment"
      working-directory: "${{ github.workspace }}/tests/archivematica"
      env:
        DOCKER_IMAGE_NAME: "rockylinux"
        DOCKER_IMAGE_TAG: "9"
      run: |
        podman-compose up --detach
    - name: Install packages
      working-directory: ${{ github.workspace }}/tests/archivematica
      run: |
        podman-compose exec \
          --env LOCAL_REPOSITORY="${{ env.build_packages }}" \
          --env ARCHIVEMATICA_PACKAGES_REPO_VERSION="${{ env.ARCHIVEMATICA_PACKAGES_REPO_VERSION }}" \
          --env ARCHIVEMATICA_PACKAGES_REPO_BASEURL="${{ env.ARCHIVEMATICA_PACKAGES_REPO_BASEURL }}" \
          --user ubuntu \
          archivematica \
          /am-packbuild/tests/archivematica/EL9/install.sh
    - name: Test AM API - Get processing configurations
      run: |
        test $( \
            curl \
                --silent \
                --header 'Authorization: ApiKey admin:apikey' \
                --header 'Content-Type: application/json' \
                'http://localhost:8000/api/processing-configuration/' \
            | jq -r '.processing_configurations == ["automated", "default"]' \
        ) == true
    - name: Test SS API - Get pipeline count
      run: |
        test $( \
            curl \
                --silent \
                --header 'Authorization: ApiKey admin:apikey' \
                --header 'Content-Type: application/json' \
                'http://localhost:8001/api/v2/pipeline/' \
            | jq -r '.meta.total_count == 1' \
        ) == true
    - name: "Save common logs on failure"
      if: ${{ failure() }}
      working-directory: "${{ github.workspace }}/tests/archivematica"
      run: |
        podman-compose exec --user root archivematica mkdir -p /tmp/logs/journalctl
        podman-compose exec --user root archivematica bash -c 'journalctl -u archivematica-mcp-client --no-pager > /tmp/logs/journalctl/archivematica-mcp-client'
    - name: "Save logs on failure"
      if: ${{ failure() }}
      working-directory: "${{ github.workspace }}/tests/archivematica"
      run: |
        podman-compose exec --user root archivematica bash -c 'journalctl -u mysqld --no-pager > /tmp/logs/journalctl/mysql'
        podman-compose exec --user root archivematica bash -c 'journalctl -u clamd@scan --no-pager > /tmp/logs/journalctl/clamd'
        podman-compose exec --user root archivematica bash -c 'cp -r /var/log/{archivematica,mysqld.log,elasticsearch,nginx} /tmp/logs'
    - name: "Copy logs from VM"
      if: ${{ failure() }}
      working-directory: "${{ github.workspace }}/tests/archivematica"
      run: |
        podman cp archivematica-package-testing_archivematica_1:/tmp/logs/ .
    - name: "Upload logs on failure"
      if: ${{ failure() }}
      uses: "actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4" # v5.0.0
      with:
        name: "logs-test-rocky9"
        path: "${{ github.workspace }}/tests/archivematica/logs"
  test-ansible:
    name: Test packages with Ansible
    needs: create-package-repo
    runs-on: ubuntu-22.04
    if: >-
      ${{
        always() && (
          needs.create-package-repo.result == 'success' ||
          (github.event_name == 'workflow_dispatch' && inputs.build_packages == false)
        )
      }}
    env:
      build_packages: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    steps:
    - name: Check out code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Restore package repository
      if: needs.create-package-repo.result == 'success'
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: package-repository
        path: ${{ github.workspace }}/rpms/EL9/_yum_repository
    - name: "Upgrade crun (supports Ubuntu's systemd in the Dockerfile)"
      run: |
        wget https://github.com/containers/crun/releases/download/1.15/crun-1.15-linux-amd64
        sudo install crun-1.15-linux-amd64 /usr/bin/crun
        rm crun-1.15-linux-amd64
    - name: "Prepare Archivematica test environment"
      uses: ./.github/actions/setup-am-tests-venv
      with:
        codename: rocky9
    - name: "Start the Compose environment"
      working-directory: "${{ github.workspace }}/tests/archivematica"
      env:
        DOCKER_IMAGE_NAME: "rockylinux"
        DOCKER_IMAGE_TAG: "9"
      run: |
        podman-compose up --detach
    - name: Install Ansible
      working-directory: ${{ github.workspace }}/tests/archivematica
      run: |
        python3 -m pip install ansible
    - name: Install the playbook requirements
      working-directory: ${{ github.workspace }}/tests/archivematica
      run: |
        ansible-galaxy install -f -p EL9/ansible/roles/ -r EL9/ansible/requirements.yml
    - name: "Adjust parsing of root's initial MySQL password in RedHat distros"
      working-directory: ${{ github.workspace }}/tests/archivematica
      run: |
        sed -i "s_cat /var/log/mysqld.log | sed -n '_journalctl --no-pager | sed -n '0,/.*temporary password is generated for root@localhost: /_g" EL9/ansible/roles/artefactual.percona/tasks/secure.yml
    - name: "Generate an SSH key"
      run: |
        mkdir $HOME/.ssh
        ssh-keygen -t rsa -f $HOME/.ssh/id_rsa -N ""
    - name: Copy your SSH public key to the container
      working-directory: ${{ github.workspace }}/tests/archivematica
      run: |
        podman-compose exec -u root archivematica bash -c 'mkdir -p /home/ubuntu/.ssh'
        podman cp $HOME/.ssh/id_rsa.pub archivematica-package-testing_archivematica_1:/home/ubuntu/.ssh/authorized_keys
        podman-compose exec -u root archivematica bash -c 'chown -R ubuntu:ubuntu /home/ubuntu/'
    - name: Run the Archivematica installation playbook
      working-directory: ${{ github.workspace }}/tests/archivematica
      run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
        export ANSIBLE_REMOTE_PORT=2222
        ansible-playbook -i localhost, EL9/ansible/playbook.yml \
            -u ubuntu \
            -e "archivematica_src_rpm_repository_use_local_baseurl=${{ env.build_packages }}" \
            -v
    - name: Test AM API - Get processing configurations
      run: |
        test $( \
            curl \
                --silent \
                --header 'Authorization: ApiKey admin:this_is_the_am_api_key' \
                --header 'Content-Type: application/json' \
                'http://localhost:8000/api/processing-configuration/' \
            | jq -r '.processing_configurations == ["automated", "default"]' \
        ) == true
    - name: Test SS API - Get pipeline count
      run: |
        test $( \
            curl \
                --silent \
                --header 'Authorization: ApiKey admin:this_is_the_ss_api_key' \
                --header 'Content-Type: application/json' \
                'http://localhost:8001/api/v2/pipeline/' \
            | jq -r '.meta.total_count == 1' \
        ) == true
    - name: "Save common logs on failure"
      if: ${{ failure() }}
      working-directory: "${{ github.workspace }}/tests/archivematica"
      run: |
        podman-compose exec --user root archivematica mkdir -p /tmp/logs/journalctl
        podman-compose exec --user root archivematica bash -c 'journalctl -u archivematica-mcp-client --no-pager > /tmp/logs/journalctl/archivematica-mcp-client'
    - name: "Save logs on failure"
      if: ${{ failure() }}
      working-directory: "${{ github.workspace }}/tests/archivematica"
      run: |
        podman-compose exec --user root archivematica bash -c 'journalctl -u mysqld --no-pager > /tmp/logs/journalctl/mysql'
        podman-compose exec --user root archivematica bash -c 'journalctl -u clamd@scan --no-pager > /tmp/logs/journalctl/clamd'
        podman-compose exec --user root archivematica bash -c 'cp -r /var/log/{archivematica,mysqld.log,elasticsearch,nginx} /tmp/logs'
    - name: "Copy logs from VM"
      if: ${{ failure() }}
      working-directory: "${{ github.workspace }}/tests/archivematica"
      run: |
        podman cp archivematica-package-testing_archivematica_1:/tmp/logs/ .
    - name: "Upload logs on failure"
      if: ${{ failure() }}
      uses: "actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4" # v5.0.0
      with:
        name: "logs-test-rocky9-ansible"
        path: "${{ github.workspace }}/tests/archivematica/logs"
