name: Archivematica RPM Packages Test
on:
  workflow_dispatch:
    inputs:
      archivematica_packages_repo_version:
        description: "Archivematica packages repository version (e.g. 1.18.x)"
        required: false
        default: "1.18.x"
        type: "string"
      archivematica_packages_repo_baseurl:
        description: "Optional Archivematica RPM repository base URL"
        required: false
        default: ""
        type: "string"
      build_packages:
        description: "Build local packages"
        required: true
        default: true
        type: "boolean"
  pull_request:
    paths:
      - ".github/actions/setup-podman-test/**"
      - ".github/workflows/test-am-rpms.yml"
      - "rpms/EL9/archivematica/**"
      - "rpms/EL9/archivematica-storage-service/**"
      - "tests/archivematica/**"
      - "!tests/archivematica/README.md"
      - "!tests/archivematica/{jammy,noble}/**"
  push:
    branches:
      - "stable/**"
      - "qa/**"
    paths:
      - ".github/actions/setup-podman-test/**"
      - ".github/workflows/test-am-rpms.yml"
      - "rpms/EL9/archivematica/**"
      - "rpms/EL9/archivematica-storage-service/**"
      - "tests/archivematica/**"
      - "!tests/archivematica/README.md"
      - "!tests/archivematica/{jammy,noble}/**"
  schedule:
    - cron: "0 2 * * *"

env:
  ARCHIVEMATICA_PACKAGES_REPO_VERSION: ${{ inputs.archivematica_packages_repo_version || '1.18.x' }}
  ARCHIVEMATICA_PACKAGES_REPO_BASEURL: ${{ inputs.archivematica_packages_repo_baseurl || '' }}
jobs:
  build-am-packages:
    name: Build Archivematica packages
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Build
      run: |
        make -C ${{ github.workspace }}/rpms/EL9/archivematica
    - name: Save artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: archivematica-packages
        path: |
          ${{ github.workspace }}/rpms/EL9/archivematica/*.rpm
  build-ss-packages:
    name: Build Storage Service packages
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Build
      run: |
        make -C ${{ github.workspace }}/rpms/EL9/archivematica-storage-service
    - name: Save artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: archivematica-storage-service-packages
        path: |
          ${{ github.workspace }}/rpms/EL9/archivematica-storage-service/*.rpm
  create-package-repo:
    name: Create package repository
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    needs:
    - build-am-packages
    - build-ss-packages
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Restore Archivematica packages
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: archivematica-packages
        path: |
          ${{ github.workspace }}/rpms/EL9/archivematica/
    - name: Restore Storage Service packages
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: archivematica-storage-service-packages
        path: |
          ${{ github.workspace }}/rpms/EL9/archivematica-storage-service
    - name: Create repository
      run: |
        make -C ${{ github.workspace }}/rpms/EL9 createrepo
    - name: Save package repository
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: package-repository
        path: |
          ${{ github.workspace }}/rpms/EL9/_yum_repository
  test:
    name: Test packages
    needs: create-package-repo
    runs-on: ubuntu-24.04
    if: >-
      ${{
        always() && (
          needs.create-package-repo.result == 'success' ||
          (github.event_name == 'workflow_dispatch' && inputs.build_packages == false)
        )
      }}
    env:
      build_packages: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Restore package repository
      if: needs.create-package-repo.result == 'success'
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: package-repository
        path: ${{ github.workspace }}/rpms/EL9/_yum_repository
    - name: "Prepare Archivematica test environment"
      uses: ./.github/actions/setup-podman-test
      with:
        environment-label: "rocky9"
        image-name: "rockylinux"
        image-tag: "9"
    - name: Install packages
      working-directory: ${{ github.workspace }}/tests/archivematica
      run: |
        podman-compose exec \
          --env LOCAL_REPOSITORY="${{ env.build_packages }}" \
          --env ARCHIVEMATICA_PACKAGES_REPO_VERSION="${{ env.ARCHIVEMATICA_PACKAGES_REPO_VERSION }}" \
          --env ARCHIVEMATICA_PACKAGES_REPO_BASEURL="${{ env.ARCHIVEMATICA_PACKAGES_REPO_BASEURL }}" \
          --user ubuntu \
          archivematica \
          /am-packbuild/tests/archivematica/EL9/install.sh
    - name: "Check Archivematica APIs"
      run: |
        tests/archivematica/common/check-archivematica-apis
    - name: "Save logs on failure"
      if: "${{ failure() || cancelled() }}"
      working-directory: "${{ github.workspace }}/tests/archivematica"
      run: |
        common/collect-test-logs logs archivematica
    - name: "Upload logs on failure"
      if: "${{ failure() || cancelled() }}"
      uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" # v7.0.1
      with:
        name: "logs-test-rocky9"
        path: "${{ github.workspace }}/tests/archivematica/logs"
  test-ansible:
    name: Test packages with Ansible
    needs: create-package-repo
    runs-on: ubuntu-24.04
    if: >-
      ${{
        always() && (
          needs.create-package-repo.result == 'success' ||
          (github.event_name == 'workflow_dispatch' && inputs.build_packages == false)
        )
      }}
    env:
      build_packages: "${{ github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.build_packages) }}"
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Restore package repository
      if: needs.create-package-repo.result == 'success'
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: package-repository
        path: ${{ github.workspace }}/rpms/EL9/_yum_repository
    - name: "Prepare Archivematica test environment"
      uses: ./.github/actions/setup-podman-test
      with:
        environment-label: "rocky9-ansible"
        image-name: "rockylinux"
        image-tag: "9"
        setup-ssh: "true"
    - name: Install Ansible
      working-directory: ${{ github.workspace }}/tests/archivematica
      run: |
        python3 -m pip install ansible
    - name: "Prepare the playbook roles"
      working-directory: "${{ github.workspace }}/tests/archivematica/EL9/ansible"
      run: |
        ../../common/prepare-ansible-roles requirements.yml
    - name: Run the Archivematica installation playbook
      working-directory: ${{ github.workspace }}/tests/archivematica
      run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
        export ANSIBLE_REMOTE_PORT=2222
        ansible-playbook -i localhost, EL9/ansible/playbook.yml \
            -u ubuntu \
            -e "archivematica_src_rpm_repository_use_local_baseurl=${{ env.build_packages }}" \
            -v
    - name: "Check Archivematica APIs"
      env:
        AM_API_KEY: "this_is_the_am_api_key"
        SS_API_KEY: "this_is_the_ss_api_key"
      run: |
        tests/archivematica/common/check-archivematica-apis
    - name: "Save logs on failure"
      if: "${{ failure() || cancelled() }}"
      working-directory: "${{ github.workspace }}/tests/archivematica"
      run: |
        common/collect-test-logs logs archivematica
    - name: "Upload logs on failure"
      if: "${{ failure() || cancelled() }}"
      uses: "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" # v7.0.1
      with:
        name: "logs-test-rocky9-ansible"
        path: "${{ github.workspace }}/tests/archivematica/logs"
