name: Archivematica Vagrant box
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version (e.g. 1.13.0-rc.2)
        required: true
      description:
        description: Description
        required: true
jobs:
  vagrant-box-archivematica:
    name: Build and upload
    runs-on: macos-latest
    env:
      PACKER_CACHE_DIR: ${{ github.workspace }}/.packer_cache
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build
      run: |
        cd ${{ github.workspace }}/packer/templates/vagrant-base-ubuntu-18.04-amd64
        packer build -on-error=abort template.json
        cd ${{ github.workspace }}/packer/templates/vagrant-box-archivematica
        packer build -on-error=abort template.json
        mv ${{ github.workspace }}/packer/builds/virtualbox/vagrant-am.box \
          ${{ github.workspace }}/archivematica-vagrant-${{ github.event.inputs.version }}.box
    - name: Upload
      run: |
        cd ${{ github.workspace }}/tools/vagrant-box-uploader
        bundle install
        ruby upload.rb \
          archivematica \
          '${{ github.workspace }}/archivematica-vagrant-${{ github.event.inputs.version }}.box' \
          '${{ secrets.VAGRANT_CLOUD }}' \
          '${{ github.event.inputs.version }}' \
          '${{ github.event.inputs.description }}'
