FROM centos:7

# Environmnet variables needed during build

# Environment variables needed during runtime

RUN yum -y install rpm-build make git wget centos-release-scl-rh gcc-c++
RUN yum -y install  rh-nodejs8-npm 
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/rh/rh-nodejs8/root/bin/
