# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.network :private_network, ip: "10.10.10.20"

  config.vm.synced_folder '.', '/home/local-transfers', mount_options: ["uid=333", "gid=333"], create: true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]
  end

end
